FROM alpine

RUN apk add nodejs npm bash curl

ARG JWT_SECRET
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG POSTGRES_DB
ARG POSTGRES_PORT

ENV JWT_SECRET $JWT_SECRET
ENV POSTGRES_USER $POSTGRES_USER
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ENV POSTGRES_HOST $POSTGRES_HOST
ENV POSTGRES_DB $POSTGRES_DB
ENV POSTGRES_PORT $POSTGRES_PORT

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .

EXPOSE 8000

CMD [ "node" , "index.js" ]
