version: '3'
services:
  server:
    container_name: 'envoix-server'
    depends_on:
      - postgres
    links:
      - postgres
    build:
      args:
        PORT:8000
        DB_NAME:envoix
        DB_HOST:postgres
        DB_PORT:5432
        DB_USER:anurag
        DB_PASS:asdf1234
        JWT_SECRET:thisissecret
      dockerfile: Dockerfile
      context: .
      ports:
        - 5000:8000

    postgres:
      image: postgres:14-alpine
      volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=asdf1234
        - POSTGRES_USER=anurag
        - POSTGRES_DB=envoix


