version: '3'
services:
  server:
    container_name: 'envoix-server'
    depends_on:
      - postgres
    links:
      - postgres
    build:
      args:
        PORT: 8000
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: envoix
        POSTGRES_PASSWORD: asdf1234
        POSTGRES_DB: envoix
        JWT_SECRET: secret
      dockerfile: Dockerfile
      context: .
    ports:
      - 9876:8000

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_USER: envoix
      POSTGRES_DB: envoix


